#!/usr/bin/env node
/**
 * `npm run check:governance` — proves the authority model holds.
 *
 * Two things it asserts, and the second is the one that matters:
 *
 *   1. the manifest is coherent — every path it names exists, and no domain
 *      declares two writable sources;
 *   2. every GENERATED artifact matches what its generator produces from its
 *      declared AUTHORITY, byte for byte.
 *
 * (2) is what makes de-authorizing a mirror safe. A gate that only validates a
 * source against itself proves nothing about the copies downstream of it, and
 * this repository shipped three mirrors of the same 66 screens for exactly that
 * reason. Regeneration happens IN MEMORY here; this command never writes.
 *
 * `--positive-control` plants drift in each generated family and fails if any
 * goes undetected. Required because a parity check with no control is
 * indistinguishable from a parity check that compares a file to itself.
 *
 * Read-only.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { ROOT, screenSource, SCREEN_OUTPUTS, SCREEN_SOURCE } from "./screenRegistry.mjs";
import { visualDocDrift } from "./visualRegistry.mjs";

const MANIFEST = "docs/couranr-mvp/authority/AUTHORITY_MANIFEST.json";
const CONTROL = process.argv.includes("--positive-control");

/** Every generated family: which authority produces it, and how. */
function outputs() {
  const src = screenSource();
  return SCREEN_OUTPUTS.map((o) => ({
    ...o,
    authority: SCREEN_SOURCE,
    source: src,
  }));
}

function firstDiff(want, got) {
  const a = want.split("\n");
  const b = got.split("\n");
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] !== b[i]) {
      return (
        `line ${i + 1}: checked-in ${JSON.stringify((a[i] ?? "").slice(0, 90))} ` +
        `vs generated ${JSON.stringify((b[i] ?? "").slice(0, 90))}`
      );
    }
  }
  return `identical by line but ${want.length} vs ${got.length} bytes (line endings or trailing newline)`;
}

/**
 * `CLAUDE.md` must not pin a value that can be measured.
 *
 * Every pattern below was live in that file at the consolidation baseline and
 * at least three were already WRONG: it claimed 1629 tests across 51 files in
 * one place and 2013 across 53 in another while the suite ran 2073 across 54,
 * and it claimed 9 of 42 work items verified while the ledger said 17. The file
 * every agent reads first was the least accurate current-state document in the
 * repository, because a hand-pinned number goes stale between the commit that
 * changes it and the commit that remembers it.
 *
 * Prose ABOUT a retired fingerprint is allowed and deliberately so — the file
 * keeps its record of which fingerprints stopped matching — so these patterns
 * match the act of pinning a CURRENT value, not the act of describing an old one.
 */
const MUTABLE_IN_CLAUDE_MD = [
  [/\*\*\d+ decision records\*\*/, "a pinned decision-record count"],
  [/\d+ canonical MVP screens/, "a pinned canonical-screen count"],
  [/\d+ of \d+ work items `complete_verified`/, "a pinned work-item completion count"],
  [/\d+ of \d+\s*\n?screens `functional_verified`/, "a pinned screen completion count"],
  [/\d+ tests across \d+ files/, "a pinned test count"],
  [/vitest run — \d+ files, \d+ tests/, "a pinned test count"],
];

function checkAgentGuidance(fail, text) {
  for (const [rx, what] of MUTABLE_IN_CLAUDE_MD) {
    const m = text.match(rx);
    if (m) {
      fail.push(
        `CLAUDE.md pins ${what} (${JSON.stringify(m[0])}) — point at ` +
          `\`npm run governance:facts\` instead; a hand-pinned count goes stale`,
      );
    }
  }
}

/** Manifest coherence. */
function checkManifest(fail) {
  if (!existsSync(join(ROOT, MANIFEST))) {
    fail.push(`${MANIFEST} does not exist — the authority model has no declaration`);
    return null;
  }
  const m = JSON.parse(readFileSync(join(ROOT, MANIFEST), "utf8"));
  const owners = new Map();

  for (const d of m.domains) {
    if (!existsSync(join(ROOT, d.authority))) {
      fail.push(`${d.domain}: declared authority "${d.authority}" does not exist`);
    }
    if (owners.has(d.authority)) {
      fail.push(
        `"${d.authority}" is declared the writable authority for BOTH ` +
          `${owners.get(d.authority)} and ${d.domain} — one source, one domain`,
      );
    }
    owners.set(d.authority, d.domain);

    for (const g of d.generated ?? []) {
      if (!existsSync(join(ROOT, g))) {
        fail.push(`${d.domain}: generated output "${g}" does not exist`);
      }
      if (owners.has(g)) {
        fail.push(`"${g}" is declared generated by ${d.domain} but is also an authority`);
      }
    }
  }

  const seen = new Set();
  for (const d of m.domains) {
    if (seen.has(d.domain)) fail.push(`domain "${d.domain}" is declared twice`);
    seen.add(d.domain);
  }
  return m;
}

/** Source -> generated parity. */
function checkParity(fail, mutate) {
  for (const o of outputs()) {
    const path = join(ROOT, o.path);
    if (!existsSync(path)) {
      fail.push(`${o.path}: declared generated but missing`);
      continue;
    }
    let checkedIn = readFileSync(path, "utf8");
    if (mutate) checkedIn = mutate(o.path, checkedIn);
    const generated = o.render(o.source);
    if (checkedIn !== generated) {
      fail.push(
        `${o.path} is not what ${o.authority} generates — ${firstDiff(checkedIn, generated)}. ` +
          `Run \`npm run governance:generate\`; do not hand-edit a generated artifact.`,
      );
    }
  }
}

const fail = [];
const manifest = checkManifest(fail);

if (CONTROL) {
  /* One plant per generated family. Each must be DETECTED; a plant that changes
     nothing is itself reported, because a control that cannot alter its input
     is a control that tested nothing. */
  let bad = 0;
  const plants = [
    ["a rewritten screen route in the generated Markdown", "UI_SCREEN_REGISTRY.md",
      (t) => t.replace("| `/pricing` |", "| `/prices` |")],
    ["a rewritten screen id in the generated CSV", "ui_screen_registry.csv",
      (t) => t.replace("PUB-008,", "PUB-808,")],
  ];
  /* The composition contract is a SOURCE, not a generated mirror, so its
     control is the other direction: prove the handbook cannot drift away from
     it unnoticed. */
  {
    const spec = join(ROOT, "docs/couranr-mvp/brand/COURANR_VISUAL_SYSTEM_V2_2.md");
    const before = readFileSync(spec, "utf8");
    const planted = before.replace(
      "| 2 | `pickup-problem` |",
      "| 2 | `pickup-problems` |",
    );
    if (planted === before) {
      console.error("positive control FAILED — could not plant a §27 table drift; the control tested nothing");
      bad++;
    } else {
      writeFileSync(spec, planted);
      let caught;
      try {
        caught = visualDocDrift(ROOT).find((f) => f.startsWith("PUB-001"));
      } finally {
        writeFileSync(spec, before);
      }
      if (!caught) {
        console.error("positive control FAILED — a §27 table that disagrees with VISUAL_REGISTRY.json was not detected");
        bad++;
      } else {
        console.log(`check:governance positive control ok — a drifted §27 table was rejected: "${caught.slice(0, 110)}"`);
      }
    }
  }
  {
    const before = readFileSync(join(ROOT, "CLAUDE.md"), "utf8");
    const detected = [];
    checkAgentGuidance(detected, before + "\n\nThere are 4321 tests across 99 files now.\n");
    if (!detected.length) {
      console.error("positive control FAILED — a re-pinned test count in CLAUDE.md was not detected");
      bad++;
    } else {
      console.log(`check:governance positive control ok — a re-pinned mutable count was rejected: "${detected[0].slice(0, 110)}"`);
    }
  }
  for (const [what, target, plant] of plants) {
    const detected = [];
    checkParity(detected, (p, text) => (p === target ? plant(text) : text));
    const original = readFileSync(join(ROOT, target), "utf8");
    if (plant(original) === original) {
      console.error(`positive control FAILED — could not plant ${what}; the control tested nothing`);
      bad++;
      continue;
    }
    const hit = detected.find((f) => f.startsWith(target));
    if (!hit) {
      console.error(`positive control FAILED — ${what} was not detected`);
      bad++;
    } else {
      console.log(`check:governance positive control ok — ${what} was rejected: "${hit.slice(0, 110)}"`);
    }
  }
  if (fail.length) {
    console.error("\npositive control ran against a repository that is already failing:");
    for (const f of fail) console.error(`  - ${f}`);
    bad++;
  }
  process.exit(bad ? 1 : 0);
}

checkParity(fail);
checkAgentGuidance(fail, readFileSync(join(ROOT, "CLAUDE.md"), "utf8"));
/* The composition contract is structured data now; §27's prose tables are the
   human view of it and must still agree. */
fail.push(...visualDocDrift(ROOT));

if (fail.length) {
  console.error(`check:governance: ${fail.length} problem(s)\n`);
  for (const f of fail) console.error(`  - ${f}`);
  process.exit(1);
}

const domains = manifest.domains.length;
const generated = manifest.domains.reduce((n, d) => n + (d.generated?.length ?? 0), 0);
const pending = (manifest.pending_domains ?? []).length;
console.log(
  `check:governance: ok — ${domains} declared domain(s), one writable source each, ` +
    `${generated} generated artifact(s) match their authority` +
    (pending ? `; ${pending} domain(s) still pending consolidation` : ""),
);
