#!/usr/bin/env node
/**
 * `npm run check:governance` — proves the authority model holds.
 *
 * Two things it asserts, and the second is the one that matters:
 *
 *   1. the manifest is coherent — every path it names exists, and no domain
 *      declares two writable sources;
 *   2. every GENERATED artifact matches what its generator produces from its
 *      declared AUTHORITY, byte for byte.
 *
 * (2) is what makes de-authorizing a mirror safe. A gate that only validates a
 * source against itself proves nothing about the copies downstream of it, and
 * this repository shipped three mirrors of the same 66 screens for exactly that
 * reason. Regeneration happens IN MEMORY here; this command never writes.
 *
 * `--positive-control` plants drift in each generated family and fails if any
 * goes undetected. Required because a parity check with no control is
 * indistinguishable from a parity check that compares a file to itself.
 *
 * Read-only.
 */
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { ROOT, screenSource, SCREEN_OUTPUTS, SCREEN_SOURCE } from "./screenRegistry.mjs";

const MANIFEST = "docs/couranr-mvp/authority/AUTHORITY_MANIFEST.json";
const CONTROL = process.argv.includes("--positive-control");

/** Every generated family: which authority produces it, and how. */
function outputs() {
  const src = screenSource();
  return SCREEN_OUTPUTS.map((o) => ({
    ...o,
    authority: SCREEN_SOURCE,
    source: src,
  }));
}

function firstDiff(want, got) {
  const a = want.split("\n");
  const b = got.split("\n");
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] !== b[i]) {
      return (
        `line ${i + 1}: checked-in ${JSON.stringify((a[i] ?? "").slice(0, 90))} ` +
        `vs generated ${JSON.stringify((b[i] ?? "").slice(0, 90))}`
      );
    }
  }
  return `identical by line but ${want.length} vs ${got.length} bytes (line endings or trailing newline)`;
}

/** Manifest coherence. */
function checkManifest(fail) {
  if (!existsSync(join(ROOT, MANIFEST))) {
    fail.push(`${MANIFEST} does not exist — the authority model has no declaration`);
    return null;
  }
  const m = JSON.parse(readFileSync(join(ROOT, MANIFEST), "utf8"));
  const owners = new Map();

  for (const d of m.domains) {
    if (!existsSync(join(ROOT, d.authority))) {
      fail.push(`${d.domain}: declared authority "${d.authority}" does not exist`);
    }
    if (owners.has(d.authority)) {
      fail.push(
        `"${d.authority}" is declared the writable authority for BOTH ` +
          `${owners.get(d.authority)} and ${d.domain} — one source, one domain`,
      );
    }
    owners.set(d.authority, d.domain);

    for (const g of d.generated ?? []) {
      if (!existsSync(join(ROOT, g))) {
        fail.push(`${d.domain}: generated output "${g}" does not exist`);
      }
      if (owners.has(g)) {
        fail.push(`"${g}" is declared generated by ${d.domain} but is also an authority`);
      }
    }
  }

  const seen = new Set();
  for (const d of m.domains) {
    if (seen.has(d.domain)) fail.push(`domain "${d.domain}" is declared twice`);
    seen.add(d.domain);
  }
  return m;
}

/** Source -> generated parity. */
function checkParity(fail, mutate) {
  for (const o of outputs()) {
    const path = join(ROOT, o.path);
    if (!existsSync(path)) {
      fail.push(`${o.path}: declared generated but missing`);
      continue;
    }
    let checkedIn = readFileSync(path, "utf8");
    if (mutate) checkedIn = mutate(o.path, checkedIn);
    const generated = o.render(o.source);
    if (checkedIn !== generated) {
      fail.push(
        `${o.path} is not what ${o.authority} generates — ${firstDiff(checkedIn, generated)}. ` +
          `Run \`npm run governance:generate\`; do not hand-edit a generated artifact.`,
      );
    }
  }
}

const fail = [];
const manifest = checkManifest(fail);

if (CONTROL) {
  /* One plant per generated family. Each must be DETECTED; a plant that changes
     nothing is itself reported, because a control that cannot alter its input
     is a control that tested nothing. */
  const plants = [
    ["a rewritten screen route in the generated Markdown", "UI_SCREEN_REGISTRY.md",
      (t) => t.replace("| `/pricing` |", "| `/prices` |")],
    ["a rewritten screen id in the generated CSV", "ui_screen_registry.csv",
      (t) => t.replace("PUB-008,", "PUB-808,")],
  ];
  let bad = 0;
  for (const [what, target, plant] of plants) {
    const detected = [];
    checkParity(detected, (p, text) => (p === target ? plant(text) : text));
    const original = readFileSync(join(ROOT, target), "utf8");
    if (plant(original) === original) {
      console.error(`positive control FAILED — could not plant ${what}; the control tested nothing`);
      bad++;
      continue;
    }
    const hit = detected.find((f) => f.startsWith(target));
    if (!hit) {
      console.error(`positive control FAILED — ${what} was not detected`);
      bad++;
    } else {
      console.log(`check:governance positive control ok — ${what} was rejected: "${hit.slice(0, 110)}"`);
    }
  }
  if (fail.length) {
    console.error("\npositive control ran against a repository that is already failing:");
    for (const f of fail) console.error(`  - ${f}`);
    bad++;
  }
  process.exit(bad ? 1 : 0);
}

checkParity(fail);

if (fail.length) {
  console.error(`check:governance: ${fail.length} problem(s)\n`);
  for (const f of fail) console.error(`  - ${f}`);
  process.exit(1);
}

const domains = manifest.domains.length;
const generated = manifest.domains.reduce((n, d) => n + (d.generated?.length ?? 0), 0);
const pending = (manifest.pending_domains ?? []).length;
console.log(
  `check:governance: ok — ${domains} declared domain(s), one writable source each, ` +
    `${generated} generated artifact(s) match their authority` +
    (pending ? `; ${pending} domain(s) still pending consolidation` : ""),
);
